"""Apply one on-policy REINFORCE update to a linear stable-pruner artifact.

The input trajectories must have been generated by the exact artifact being updated.
This tool intentionally performs one batch update only; collect a fresh trajectory batch
after every artifact update rather than repeatedly optimizing stale behavior-policy data.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import subprocess
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_SRC_ROOT = Path(__file__).resolve().parent.parent / "src"
_REPO_ROOT = _SRC_ROOT.parent
if str(_SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(_SRC_ROOT))

from sts2_training.decision.learned_pruner import (
    LEARNED_PRUNER_ARTIFACT_SCHEMA_VERSION,
    LinearStableFrontierPruner,
)
from sts2_training.decision.pruner_features import (
    PRUNER_FEATURE_NAMES,
    PRUNER_FEATURE_SCHEMA_VERSION,
)
from sts2_training.decision.pruner_rl import (
    plackett_luce_log_probability,
    plackett_luce_logprob_gradient,
)
from sts2_training.decision.stable_pruner import STABLE_PRUNE_NODE_VIEW_SCHEMA_VERSION
from sts2_training.runner.stable_pruner_rl import RL_TRAJECTORY_SCHEMA_VERSION

_INTEGRITY_REL_TOL = 1e-9
_INTEGRITY_ABS_TOL = 1e-9


@dataclass(frozen=True)
class RLUpdateExample:
    reward: float
    steps: tuple[Mapping[str, Any], ...]
    source_path: str
    line_number: int


@dataclass(frozen=True)
class RLUpdateResult:
    examples: int
    stochastic_steps: int
    mean_reward: float
    positive_reward_examples: int
    negative_reward_examples: int
    zero_reward_examples: int
    raw_gradient_norm: float
    applied_gradient_norm: float
    coefficient_delta_norm: float


def load_update_examples(
    paths: Sequence[Path],
    *,
    expected_artifact_sha256: str,
    coefficients: Sequence[float],
    scale: Sequence[float],
) -> list[RLUpdateExample]:
    examples: list[RLUpdateExample] = []
    for path in paths:
        with path.open("r", encoding="utf-8") as handle:
            for line_number, line in enumerate(handle, start=1):
                if not line.strip():
                    continue
                raw = json.loads(line)
                source = f"{path}:{line_number}"
                if not isinstance(raw, Mapping):
                    raise ValueError(f"{source}: trajectory record must be an object")
                if raw.get("record_type") != "stable_pruner_rl_episode":
                    continue
                if raw.get("record_schema_version") != RL_TRAJECTORY_SCHEMA_VERSION:
                    raise ValueError(
                        f"{source}: unsupported RL trajectory schema "
                        f"{raw.get('record_schema_version')!r}"
                    )
                behavior = raw.get("behavior")
                if not isinstance(behavior, Mapping):
                    raise ValueError(f"{source}: missing behavior provenance")
                _validate_behavior_contract(
                    behavior,
                    expected_artifact_sha256=expected_artifact_sha256,
                    source=source,
                )
                reward_payload = raw.get("reward")
                if not isinstance(reward_payload, Mapping):
                    raise ValueError(f"{source}: missing reward")
                reward = _validate_reward_contract(raw, reward_payload, source=source)
                steps_raw = raw.get("steps")
                if not isinstance(steps_raw, Sequence) or isinstance(
                    steps_raw, (str, bytes, bytearray)
                ):
                    raise ValueError(f"{source}: steps must be a sequence")
                steps = tuple(step for step in steps_raw if isinstance(step, Mapping))
                if len(steps) != len(steps_raw) or not steps:
                    raise ValueError(f"{source}: steps must contain objects")
                for step in steps:
                    _validate_behavior_step(
                        step,
                        behavior=behavior,
                        coefficients=coefficients,
                        scale=scale,
                        source=source,
                    )
                examples.append(
                    RLUpdateExample(
                        reward=reward,
                        steps=steps,
                        source_path=str(path),
                        line_number=line_number,
                    )
                )
    if not examples:
        raise ValueError("no stable_pruner_rl_episode records found")
    return examples


def apply_reinforce_update(
    coefficients: Sequence[float],
    scale: Sequence[float],
    examples: Sequence[RLUpdateExample],
    *,
    learning_rate: float,
    gradient_clip_norm: float,
) -> tuple[list[float], RLUpdateResult]:
    _validate_positive_finite("learning_rate", learning_rate)
    _validate_positive_finite("gradient_clip_norm", gradient_clip_norm)
    if not examples:
        raise ValueError("examples must not be empty")
    width = len(coefficients)
    if len(scale) != width:
        raise ValueError("scale must match coefficients")
    gradient = [0.0] * width
    step_count = 0

    for example in examples:
        episode_gradient = [0.0] * width
        for step in example.steps:
            feature_rows = _feature_rows(step, width=width)
            scores = tuple(
                _linear_score(row, coefficients=coefficients, scale=scale)
                for row in feature_rows
            )
            sampled_indices = _sampled_indices(step, frontier_size=len(feature_rows))
            temperature = _finite_float(step.get("temperature"), "step.temperature")
            step_gradient = plackett_luce_logprob_gradient(
                scores,
                feature_rows,
                sampled_indices,
                temperature=temperature,
                scale=scale,
            )
            for index, value in enumerate(step_gradient):
                episode_gradient[index] += value
            step_count += 1
        for index, value in enumerate(episode_gradient):
            gradient[index] += example.reward * value

    inv_examples = 1.0 / len(examples)
    gradient = [value * inv_examples for value in gradient]
    raw_norm = math.sqrt(sum(value * value for value in gradient))
    if raw_norm > float(gradient_clip_norm):
        factor = float(gradient_clip_norm) / raw_norm
        applied = [value * factor for value in gradient]
    else:
        applied = gradient
    applied_norm = math.sqrt(sum(value * value for value in applied))
    delta = [float(learning_rate) * value for value in applied]
    updated = [float(value) + change for value, change in zip(coefficients, delta, strict=True)]
    if not all(math.isfinite(value) for value in updated):
        raise ValueError("RL update produced non-finite coefficients")
    delta_norm = math.sqrt(sum(value * value for value in delta))
    rewards = [example.reward for example in examples]
    return updated, RLUpdateResult(
        examples=len(examples),
        stochastic_steps=step_count,
        mean_reward=sum(rewards) / len(rewards),
        positive_reward_examples=sum(value > 0 for value in rewards),
        negative_reward_examples=sum(value < 0 for value in rewards),
        zero_reward_examples=sum(value == 0 for value in rewards),
        raw_gradient_norm=raw_norm,
        applied_gradient_norm=applied_norm,
        coefficient_delta_norm=delta_norm,
    )


def updated_artifact_payload(
    base_payload: Mapping[str, Any],
    *,
    base_artifact_sha256: str,
    coefficients: Sequence[float],
    result: RLUpdateResult,
    trajectory_files: Sequence[Path],
    learning_rate: float,
    gradient_clip_norm: float,
) -> dict[str, Any]:
    """Return an artifact-schema-v2 payload with an appended on-policy audit record."""

    _require_base_artifact_contract(base_payload)
    payload = dict(base_payload)
    history_raw = payload.get("rl_finetuning_history")
    history = list(history_raw) if isinstance(history_raw, list) else []
    trajectory_inputs = [
        {"path": str(path), "sha256": _file_sha256(path)} for path in trajectory_files
    ]
    update = {
        "updated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "training_commit": _training_commit(),
        "parent_artifact_sha256": base_artifact_sha256,
        # Keep the original path-only field for artifact compatibility while making exact
        # trajectory bytes independently auditable.
        "trajectory_files": [str(path) for path in trajectory_files],
        "trajectory_inputs": trajectory_inputs,
        "learning_rate": float(learning_rate),
        "gradient_clip_norm": float(gradient_clip_norm),
        "algorithm": "paired_on_policy_reinforce_plackett_luce",
        "behavior_contract": {
            "rl_trajectory_schema_version": RL_TRAJECTORY_SCHEMA_VERSION,
            "artifact_schema_version": LEARNED_PRUNER_ARTIFACT_SCHEMA_VERSION,
            "stable_prune_node_view_schema_version": STABLE_PRUNE_NODE_VIEW_SCHEMA_VERSION,
            "feature_schema_version": PRUNER_FEATURE_SCHEMA_VERSION,
        },
        "result": result.__dict__,
    }
    history.append(update)
    payload["coefficients"] = [float(value) for value in coefficients]
    payload["rl_finetuning_history"] = history
    payload["last_rl_update"] = update
    return payload


def _validate_behavior_contract(
    behavior: Mapping[str, Any],
    *,
    expected_artifact_sha256: str,
    source: str,
) -> None:
    artifact_sha = behavior.get("artifact_sha256")
    if artifact_sha != expected_artifact_sha256:
        raise ValueError(
            f"{source}: behavior artifact {artifact_sha!r} does not match update base "
            f"{expected_artifact_sha256!r}"
        )
    _require_schema(
        behavior,
        "artifact_schema_version",
        LEARNED_PRUNER_ARTIFACT_SCHEMA_VERSION,
        source,
    )
    _require_schema(
        behavior,
        "stable_prune_node_view_schema_version",
        STABLE_PRUNE_NODE_VIEW_SCHEMA_VERSION,
        source,
    )
    _require_schema(
        behavior,
        "feature_schema_version",
        PRUNER_FEATURE_SCHEMA_VERSION,
        source,
    )
    temperature = _finite_float(behavior.get("temperature"), f"{source}: behavior.temperature")
    if temperature <= 0:
        raise ValueError(f"{source}: behavior.temperature must be positive")
    _integer(behavior.get("sampler_seed"), f"{source}: behavior.sampler_seed")


def _validate_behavior_step(
    step: Mapping[str, Any],
    *,
    behavior: Mapping[str, Any],
    coefficients: Sequence[float],
    scale: Sequence[float],
    source: str,
) -> None:
    _require_schema(
        step,
        "stable_prune_node_view_schema_version",
        STABLE_PRUNE_NODE_VIEW_SCHEMA_VERSION,
        f"{source}: step",
    )
    _require_schema(
        step,
        "feature_schema_version",
        PRUNER_FEATURE_SCHEMA_VERSION,
        f"{source}: step",
    )
    rows = _feature_rows(step, width=len(coefficients))
    logged_scores = step.get("behavior_scores")
    if not isinstance(logged_scores, Sequence) or isinstance(
        logged_scores, (str, bytes, bytearray)
    ):
        raise ValueError(f"{source}: behavior_scores must be a sequence")
    if len(logged_scores) != len(rows):
        raise ValueError(f"{source}: behavior_scores length mismatch")
    recomputed = [
        _linear_score(row, coefficients=coefficients, scale=scale) for row in rows
    ]
    for index, (logged, actual) in enumerate(zip(logged_scores, recomputed, strict=True)):
        logged_value = _finite_float(logged, f"{source}: behavior_scores[{index}]")
        if not math.isclose(
            logged_value,
            actual,
            rel_tol=_INTEGRITY_REL_TOL,
            abs_tol=_INTEGRITY_ABS_TOL,
        ):
            raise ValueError(
                f"{source}: behavior score does not match base artifact at index {index}"
            )

    beam_width = _positive_int(step.get("beam_width"), f"{source}: beam_width")
    if len(rows) <= beam_width:
        raise ValueError(f"{source}: RL step must represent an actual pruning choice")
    sampled_indices = _sampled_indices(step, frontier_size=len(rows))
    if len(sampled_indices) != beam_width:
        raise ValueError(f"{source}: sampled_indices length must equal beam_width")
    returned_indices = _returned_indices(step, frontier_size=len(rows))
    if len(returned_indices) != len(sampled_indices) or set(returned_indices) != set(
        sampled_indices
    ):
        raise ValueError(f"{source}: returned_indices must contain exactly the sampled set")
    selected_set = set(sampled_indices)
    base_order = sorted(range(len(rows)), key=lambda index: recomputed[index], reverse=True)
    expected_returned = tuple(index for index in base_order if index in selected_set)
    if returned_indices != expected_returned:
        raise ValueError(f"{source}: returned_indices do not match deterministic survivor order")

    temperature = _finite_float(step.get("temperature"), f"{source}: step.temperature")
    if temperature <= 0:
        raise ValueError(f"{source}: step.temperature must be positive")
    behavior_temperature = _finite_float(
        behavior.get("temperature"), f"{source}: behavior.temperature"
    )
    if temperature != behavior_temperature:
        raise ValueError(f"{source}: step.temperature does not match behavior.temperature")
    sampler_seed = _integer(step.get("sampler_seed"), f"{source}: step.sampler_seed")
    behavior_seed = _integer(
        behavior.get("sampler_seed"), f"{source}: behavior.sampler_seed"
    )
    if sampler_seed != behavior_seed:
        raise ValueError(f"{source}: step.sampler_seed does not match behavior.sampler_seed")

    expected_logp = plackett_luce_log_probability(
        recomputed,
        sampled_indices,
        temperature=temperature,
    )
    logged_logp = _finite_float(
        step.get("selection_log_probability"),
        f"{source}: selection_log_probability",
    )
    if not math.isclose(
        logged_logp,
        expected_logp,
        rel_tol=_INTEGRITY_REL_TOL,
        abs_tol=_INTEGRITY_ABS_TOL,
    ):
        raise ValueError(f"{source}: selection_log_probability does not match behavior policy")


def _validate_reward_contract(
    record: Mapping[str, Any], reward: Mapping[str, Any], *, source: str
) -> float:
    outcome_delta = _finite_float(reward.get("outcome_delta"), f"{source}: reward.outcome_delta")
    nodes_delta = _integer(
        reward.get("nodes_expanded_delta"), f"{source}: reward.nodes_expanded_delta"
    )
    beam_ms_delta = _finite_float(
        reward.get("beam_ms_delta"), f"{source}: reward.beam_ms_delta"
    )
    node_cost_weight = _finite_float(
        reward.get("node_cost_weight"), f"{source}: reward.node_cost_weight"
    )
    beam_ms_cost_weight = _finite_float(
        reward.get("beam_ms_cost_weight"), f"{source}: reward.beam_ms_cost_weight"
    )
    if node_cost_weight < 0 or beam_ms_cost_weight < 0:
        raise ValueError(f"{source}: reward cost weights must be non-negative")
    total = _finite_float(reward.get("total"), f"{source}: reward.total")
    recomputed_total = (
        outcome_delta - node_cost_weight * nodes_delta - beam_ms_cost_weight * beam_ms_delta
    )
    _require_close(total, recomputed_total, f"{source}: reward.total")

    paired = record.get("paired_result")
    if not isinstance(paired, Mapping):
        raise ValueError(f"{source}: missing paired_result")
    baseline_score = _outcome_score(paired.get("baseline_outcome"))
    learned_score = _outcome_score(paired.get("learned_outcome"))
    if baseline_score is None or learned_score is None:
        raise ValueError(f"{source}: paired_result outcomes must be resolved win/loss values")
    _require_close(
        outcome_delta,
        learned_score - baseline_score,
        f"{source}: reward.outcome_delta",
    )

    baseline_nodes = _integer(
        paired.get("baseline_nodes_expanded"), f"{source}: paired_result.baseline_nodes_expanded"
    )
    learned_nodes = _integer(
        paired.get("learned_nodes_expanded"), f"{source}: paired_result.learned_nodes_expanded"
    )
    if nodes_delta != learned_nodes - baseline_nodes:
        raise ValueError(f"{source}: reward.nodes_expanded_delta does not match paired_result")

    baseline_beam_ms = _finite_float(
        paired.get("baseline_beam_total_ms"), f"{source}: paired_result.baseline_beam_total_ms"
    )
    learned_beam_ms = _finite_float(
        paired.get("learned_beam_total_ms"), f"{source}: paired_result.learned_beam_total_ms"
    )
    _require_close(
        beam_ms_delta,
        learned_beam_ms - baseline_beam_ms,
        f"{source}: reward.beam_ms_delta",
    )
    return total


def _outcome_score(value: Any) -> float | None:
    if not isinstance(value, str):
        return None
    normalized = value.strip().lower()
    if normalized in {"victory", "win"}:
        return 1.0
    if normalized in {"defeat", "loss"}:
        return 0.0
    return None


def _require_close(actual: float, expected: float, field: str) -> None:
    if not math.isclose(
        actual,
        expected,
        rel_tol=_INTEGRITY_REL_TOL,
        abs_tol=_INTEGRITY_ABS_TOL,
    ):
        raise ValueError(f"{field} does not match recomputed trajectory value")


def _feature_rows(step: Mapping[str, Any], *, width: int) -> tuple[tuple[float, ...], ...]:
    raw_rows = step.get("frontier_features")
    if not isinstance(raw_rows, Sequence) or isinstance(raw_rows, (str, bytes, bytearray)):
        raise ValueError("step.frontier_features must be a sequence")
    rows: list[tuple[float, ...]] = []
    for raw_row in raw_rows:
        if not isinstance(raw_row, Sequence) or isinstance(raw_row, (str, bytes, bytearray)):
            raise ValueError("each frontier feature row must be a sequence")
        if len(raw_row) != width:
            raise ValueError("frontier feature width does not match artifact")
        rows.append(tuple(_finite_float(value, "frontier feature") for value in raw_row))
    if not rows:
        raise ValueError("frontier_features must not be empty")
    return tuple(rows)


def _sampled_indices(step: Mapping[str, Any], *, frontier_size: int) -> tuple[int, ...]:
    return _index_sequence(
        step.get("sampled_indices"),
        frontier_size=frontier_size,
        field="sampled_indices",
    )


def _returned_indices(step: Mapping[str, Any], *, frontier_size: int) -> tuple[int, ...]:
    return _index_sequence(
        step.get("returned_indices"),
        frontier_size=frontier_size,
        field="returned_indices",
    )


def _index_sequence(raw: Any, *, frontier_size: int, field: str) -> tuple[int, ...]:
    if not isinstance(raw, Sequence) or isinstance(raw, (str, bytes, bytearray)):
        raise ValueError(f"step.{field} must be a sequence")
    result: list[int] = []
    for value in raw:
        if isinstance(value, bool) or not isinstance(value, int):
            raise ValueError(f"{field} must contain integers")
        if value < 0 or value >= frontier_size or value in result:
            raise ValueError(f"{field} must be unique valid frontier indices")
        result.append(value)
    if not result:
        raise ValueError(f"{field} must not be empty")
    return tuple(result)


def _linear_score(
    row: Sequence[float],
    *,
    coefficients: Sequence[float],
    scale: Sequence[float],
) -> float:
    return sum(
        float(coefficient) * (float(value) / float(factor))
        for coefficient, value, factor in zip(coefficients, row, scale, strict=True)
    )


def _require_base_artifact_contract(base_payload: Mapping[str, Any]) -> None:
    _require_schema(
        base_payload,
        "artifact_schema_version",
        LEARNED_PRUNER_ARTIFACT_SCHEMA_VERSION,
        "artifact",
    )
    _require_schema(
        base_payload,
        "stable_prune_node_view_schema_version",
        STABLE_PRUNE_NODE_VIEW_SCHEMA_VERSION,
        "artifact",
    )
    _require_schema(
        base_payload,
        "feature_schema_version",
        PRUNER_FEATURE_SCHEMA_VERSION,
        "artifact",
    )


def _require_schema(
    payload: Mapping[str, Any], field: str, expected: int, source: str
) -> None:
    if payload.get(field) != expected:
        raise ValueError(f"{source}: {field} mismatch")


def _finite_float(value: Any, field: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{field} must be numeric")
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{field} must be finite")
    return result


def _integer(value: Any, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{field} must be an integer")
    return value


def _positive_int(value: Any, field: str) -> int:
    result = _integer(value, field)
    if result <= 0:
        raise ValueError(f"{field} must be a positive integer")
    return result


def _validate_positive_finite(name: str, value: float) -> None:
    result = _finite_float(value, name)
    if result <= 0:
        raise ValueError(f"{name} must be positive")


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _training_commit() -> str | None:
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=_REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    value = completed.stdout.strip()
    return value or None


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--weights", type=Path, required=True)
    parser.add_argument("--trajectory", type=Path, action="append", required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("tools/output/stable_pruner_rl_weights.json"),
    )
    parser.add_argument("--learning-rate", type=float, default=0.01)
    parser.add_argument("--gradient-clip-norm", type=float, default=5.0)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    raw = args.weights.read_bytes()
    base_sha = hashlib.sha256(raw).hexdigest()
    base_payload = json.loads(raw.decode("utf-8"))
    if not isinstance(base_payload, Mapping):
        raise ValueError("learned pruner artifact must be a JSON object")

    # Reuse runtime validation for model/artifact/node-view/feature schema and finite weights.
    LinearStableFrontierPruner.from_weights_file(args.weights)
    _require_base_artifact_contract(base_payload)
    if tuple(base_payload.get("feature_names") or ()) != PRUNER_FEATURE_NAMES:
        raise ValueError("artifact feature_names do not match runtime schema")
    coefficients = tuple(
        _finite_float(value, "artifact coefficient")
        for value in base_payload.get("coefficients") or ()
    )
    scale = tuple(
        _finite_float(value, "artifact scale") for value in base_payload.get("scale") or ()
    )
    if len(coefficients) != len(PRUNER_FEATURE_NAMES) or len(scale) != len(coefficients):
        raise ValueError("artifact coefficient/scale width mismatch")
    if not all(value > 0 for value in scale):
        raise ValueError("artifact scale must be positive")

    examples = load_update_examples(
        args.trajectory,
        expected_artifact_sha256=base_sha,
        coefficients=coefficients,
        scale=scale,
    )
    updated, result = apply_reinforce_update(
        coefficients,
        scale,
        examples,
        learning_rate=args.learning_rate,
        gradient_clip_norm=args.gradient_clip_norm,
    )
    payload = updated_artifact_payload(
        base_payload,
        base_artifact_sha256=base_sha,
        coefficients=updated,
        result=result,
        trajectory_files=args.trajectory,
        learning_rate=args.learning_rate,
        gradient_clip_norm=args.gradient_clip_norm,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps(result.__dict__, indent=2, sort_keys=True))
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
