"""Apply one on-policy REINFORCE update to a linear stable-pruner artifact.

The input trajectories must have been generated by the exact artifact being updated.
This tool intentionally performs one batch update only; collect a fresh trajectory batch
after every artifact update rather than repeatedly optimizing stale behavior-policy data.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

_SRC_ROOT = Path(__file__).resolve().parent.parent / "src"
_REPO_ROOT = _SRC_ROOT.parent
if str(_SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(_SRC_ROOT))

from sts2_training.decision.learned_pruner import (
    LEARNED_PRUNER_ARTIFACT_SCHEMA_VERSION,
    LinearStableFrontierPruner,
)
from sts2_training.decision.pruner_features import (
    PRUNER_FEATURE_NAMES,
    PRUNER_FEATURE_SCHEMA_VERSION,
)
from sts2_training.decision.pruner_rl import (
    plackett_luce_log_probability,
    plackett_luce_logprob_gradient,
)
from sts2_training.runner.stable_pruner_rl import RL_TRAJECTORY_SCHEMA_VERSION


@dataclass(frozen=True)
class RLUpdateExample:
    reward: float
    steps: tuple[Mapping[str, Any], ...]
    source_path: str
    line_number: int


@dataclass(frozen=True)
class RLUpdateResult:
    examples: int
    stochastic_steps: int
    mean_reward: float
    positive_reward_examples: int
    negative_reward_examples: int
    zero_reward_examples: int
    raw_gradient_norm: float
    applied_gradient_norm: float
    coefficient_delta_norm: float


def load_update_examples(
    paths: Sequence[Path],
    *,
    expected_artifact_sha256: str,
    coefficients: Sequence[float],
    scale: Sequence[float],
) -> list[RLUpdateExample]:
    examples: list[RLUpdateExample] = []
    for path in paths:
        with path.open("r", encoding="utf-8") as handle:
            for line_number, line in enumerate(handle, start=1):
                if not line.strip():
                    continue
                raw = json.loads(line)
                if not isinstance(raw, Mapping):
                    raise ValueError(f"{path}:{line_number}: trajectory record must be an object")
                if raw.get("record_type") != "stable_pruner_rl_episode":
                    continue
                if raw.get("record_schema_version") != RL_TRAJECTORY_SCHEMA_VERSION:
                    raise ValueError(
                        f"{path}:{line_number}: unsupported RL trajectory schema "
                        f"{raw.get('record_schema_version')!r}"
                    )
                behavior = raw.get("behavior")
                if not isinstance(behavior, Mapping):
                    raise ValueError(f"{path}:{line_number}: missing behavior provenance")
                artifact_sha = behavior.get("artifact_sha256")
                if artifact_sha != expected_artifact_sha256:
                    raise ValueError(
                        f"{path}:{line_number}: behavior artifact {artifact_sha!r} does not "
                        f"match update base {expected_artifact_sha256!r}"
                    )
                reward_payload = raw.get("reward")
                if not isinstance(reward_payload, Mapping):
                    raise ValueError(f"{path}:{line_number}: missing reward")
                reward = _finite_float(
                    reward_payload.get("total"),
                    f"{path}:{line_number}: reward.total",
                )
                steps_raw = raw.get("steps")
                if not isinstance(steps_raw, Sequence) or isinstance(
                    steps_raw, (str, bytes, bytearray)
                ):
                    raise ValueError(f"{path}:{line_number}: steps must be a sequence")
                steps = tuple(step for step in steps_raw if isinstance(step, Mapping))
                if len(steps) != len(steps_raw) or not steps:
                    raise ValueError(f"{path}:{line_number}: steps must contain objects")
                for step in steps:
                    _validate_behavior_step(
                        step,
                        coefficients=coefficients,
                        scale=scale,
                        source=f"{path}:{line_number}",
                    )
                examples.append(
                    RLUpdateExample(
                        reward=reward,
                        steps=steps,
                        source_path=str(path),
                        line_number=line_number,
                    )
                )
    if not examples:
        raise ValueError("no stable_pruner_rl_episode records found")
    return examples


def apply_reinforce_update(
    coefficients: Sequence[float],
    scale: Sequence[float],
    examples: Sequence[RLUpdateExample],
    *,
    learning_rate: float,
    gradient_clip_norm: float,
) -> tuple[list[float], RLUpdateResult]:
    _validate_positive_finite("learning_rate", learning_rate)
    _validate_positive_finite("gradient_clip_norm", gradient_clip_norm)
    if not examples:
        raise ValueError("examples must not be empty")
    width = len(coefficients)
    if len(scale) != width:
        raise ValueError("scale must match coefficients")
    gradient = [0.0] * width
    step_count = 0

    for example in examples:
        episode_gradient = [0.0] * width
        for step in example.steps:
            feature_rows = _feature_rows(step, width=width)
            scores = tuple(
                _linear_score(row, coefficients=coefficients, scale=scale)
                for row in feature_rows
            )
            sampled_indices = _sampled_indices(step, frontier_size=len(feature_rows))
            temperature = _finite_float(step.get("temperature"), "step.temperature")
            step_gradient = plackett_luce_logprob_gradient(
                scores,
                feature_rows,
                sampled_indices,
                temperature=temperature,
                scale=scale,
            )
            for index, value in enumerate(step_gradient):
                episode_gradient[index] += value
            step_count += 1
        for index, value in enumerate(episode_gradient):
            gradient[index] += example.reward * value

    inv_examples = 1.0 / len(examples)
    gradient = [value * inv_examples for value in gradient]
    raw_norm = math.sqrt(sum(value * value for value in gradient))
    if raw_norm > float(gradient_clip_norm):
        factor = float(gradient_clip_norm) / raw_norm
        applied = [value * factor for value in gradient]
    else:
        applied = gradient
    applied_norm = math.sqrt(sum(value * value for value in applied))
    delta = [float(learning_rate) * value for value in applied]
    updated = [float(value) + change for value, change in zip(coefficients, delta, strict=True)]
    if not all(math.isfinite(value) for value in updated):
        raise ValueError("RL update produced non-finite coefficients")
    delta_norm = math.sqrt(sum(value * value for value in delta))
    rewards = [example.reward for example in examples]
    return updated, RLUpdateResult(
        examples=len(examples),
        stochastic_steps=step_count,
        mean_reward=sum(rewards) / len(rewards),
        positive_reward_examples=sum(value > 0 for value in rewards),
        negative_reward_examples=sum(value < 0 for value in rewards),
        zero_reward_examples=sum(value == 0 for value in rewards),
        raw_gradient_norm=raw_norm,
        applied_gradient_norm=applied_norm,
        coefficient_delta_norm=delta_norm,
    )


def updated_artifact_payload(
    base_payload: Mapping[str, Any],
    *,
    base_artifact_sha256: str,
    coefficients: Sequence[float],
    result: RLUpdateResult,
    trajectory_files: Sequence[Path],
    learning_rate: float,
    gradient_clip_norm: float,
) -> dict[str, Any]:
    payload = dict(base_payload)
    history_raw = payload.get("rl_finetuning_history")
    history = list(history_raw) if isinstance(history_raw, list) else []
    update = {
        "updated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "training_commit": _training_commit(),
        "parent_artifact_sha256": base_artifact_sha256,
        "trajectory_files": [str(path) for path in trajectory_files],
        "learning_rate": float(learning_rate),
        "gradient_clip_norm": float(gradient_clip_norm),
        "algorithm": "paired_on_policy_reinforce_plackett_luce",
        "result": result.__dict__,
    }
    history.append(update)
    payload["coefficients"] = [float(value) for value in coefficients]
    payload["rl_finetuning_history"] = history
    payload["last_rl_update"] = update
    return payload


def _validate_behavior_step(
    step: Mapping[str, Any],
    *,
    coefficients: Sequence[float],
    scale: Sequence[float],
    source: str,
) -> None:
    if step.get("feature_schema_version") != PRUNER_FEATURE_SCHEMA_VERSION:
        raise ValueError(f"{source}: step feature schema mismatch")
    rows = _feature_rows(step, width=len(coefficients))
    logged_scores = step.get("behavior_scores")
    if not isinstance(logged_scores, Sequence) or isinstance(
        logged_scores, (str, bytes, bytearray)
    ):
        raise ValueError(f"{source}: behavior_scores must be a sequence")
    if len(logged_scores) != len(rows):
        raise ValueError(f"{source}: behavior_scores length mismatch")
    recomputed = [
        _linear_score(row, coefficients=coefficients, scale=scale) for row in rows
    ]
    for index, (logged, actual) in enumerate(zip(logged_scores, recomputed, strict=True)):
        logged_value = _finite_float(logged, f"{source}: behavior_scores[{index}]")
        if not math.isclose(logged_value, actual, rel_tol=1e-9, abs_tol=1e-9):
            raise ValueError(
                f"{source}: behavior score does not match base artifact at index {index}"
            )
    sampled_indices = _sampled_indices(step, frontier_size=len(rows))
    temperature = _finite_float(step.get("temperature"), f"{source}: temperature")
    if temperature <= 0:
        raise ValueError(f"{source}: temperature must be positive")
    expected_logp = plackett_luce_log_probability(
        recomputed,
        sampled_indices,
        temperature=temperature,
    )
    logged_logp = _finite_float(
        step.get("selection_log_probability"),
        f"{source}: selection_log_probability",
    )
    if not math.isclose(logged_logp, expected_logp, rel_tol=1e-9, abs_tol=1e-9):
        raise ValueError(f"{source}: selection_log_probability does not match behavior policy")


def _feature_rows(step: Mapping[str, Any], *, width: int) -> tuple[tuple[float, ...], ...]:
    raw_rows = step.get("frontier_features")
    if not isinstance(raw_rows, Sequence) or isinstance(raw_rows, (str, bytes, bytearray)):
        raise ValueError("step.frontier_features must be a sequence")
    rows: list[tuple[float, ...]] = []
    for raw_row in raw_rows:
        if not isinstance(raw_row, Sequence) or isinstance(raw_row, (str, bytes, bytearray)):
            raise ValueError("each frontier feature row must be a sequence")
        if len(raw_row) != width:
            raise ValueError("frontier feature width does not match artifact")
        row = tuple(_finite_float(value, "frontier feature") for value in raw_row)
        rows.append(row)
    if not rows:
        raise ValueError("frontier_features must not be empty")
    return tuple(rows)


def _sampled_indices(step: Mapping[str, Any], *, frontier_size: int) -> tuple[int, ...]:
    raw = step.get("sampled_indices")
    if not isinstance(raw, Sequence) or isinstance(raw, (str, bytes, bytearray)):
        raise ValueError("step.sampled_indices must be a sequence")
    result: list[int] = []
    for value in raw:
        if isinstance(value, bool) or not isinstance(value, int):
            raise ValueError("sampled_indices must contain integers")
        if value < 0 or value >= frontier_size or value in result:
            raise ValueError("sampled_indices must be unique valid frontier indices")
        result.append(value)
    if not result:
        raise ValueError("sampled_indices must not be empty")
    return tuple(result)


def _linear_score(
    row: Sequence[float],
    *,
    coefficients: Sequence[float],
    scale: Sequence[float],
) -> float:
    return sum(
        float(coefficient) * (float(value) / float(factor))
        for coefficient, value, factor in zip(coefficients, row, scale, strict=True)
    )


def _finite_float(value: Any, field: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{field} must be numeric")
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{field} must be finite")
    return result


def _validate_positive_finite(name: str, value: float) -> None:
    result = _finite_float(value, name)
    if result <= 0:
        raise ValueError(f"{name} must be positive")


def _training_commit() -> str | None:
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=_REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    value = completed.stdout.strip()
    return value or None


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--weights", type=Path, required=True)
    parser.add_argument("--trajectory", type=Path, action="append", required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("tools/output/stable_pruner_rl_weights.json"),
    )
    parser.add_argument("--learning-rate", type=float, default=0.01)
    parser.add_argument("--gradient-clip-norm", type=float, default=5.0)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    raw = args.weights.read_bytes()
    base_sha = hashlib.sha256(raw).hexdigest()
    base_payload = json.loads(raw.decode("utf-8"))
    if not isinstance(base_payload, Mapping):
        raise ValueError("learned pruner artifact must be a JSON object")

    # Reuse runtime validation for model/artifact/feature schema and finite weights.
    LinearStableFrontierPruner.from_weights_file(args.weights)
    if base_payload.get("artifact_schema_version") != LEARNED_PRUNER_ARTIFACT_SCHEMA_VERSION:
        raise ValueError("unsupported learned-pruner artifact schema")
    if tuple(base_payload.get("feature_names") or ()) != PRUNER_FEATURE_NAMES:
        raise ValueError("artifact feature_names do not match runtime schema")
    coefficients = tuple(
        _finite_float(value, "artifact coefficient")
        for value in base_payload.get("coefficients") or ()
    )
    scale = tuple(
        _finite_float(value, "artifact scale") for value in base_payload.get("scale") or ()
    )
    if len(coefficients) != len(PRUNER_FEATURE_NAMES) or len(scale) != len(coefficients):
        raise ValueError("artifact coefficient/scale width mismatch")
    if not all(value > 0 for value in scale):
        raise ValueError("artifact scale must be positive")

    examples = load_update_examples(
        args.trajectory,
        expected_artifact_sha256=base_sha,
        coefficients=coefficients,
        scale=scale,
    )
    updated, result = apply_reinforce_update(
        coefficients,
        scale,
        examples,
        learning_rate=args.learning_rate,
        gradient_clip_norm=args.gradient_clip_norm,
    )
    payload = updated_artifact_payload(
        base_payload,
        base_artifact_sha256=base_sha,
        coefficients=updated,
        result=result,
        trajectory_files=args.trajectory,
        learning_rate=args.learning_rate,
        gradient_clip_norm=args.gradient_clip_norm,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps(result.__dict__, indent=2, sort_keys=True))
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
